name: Calculator
main: fr.andross.calculator.Calculator
version: '1.0'
author: Andross
description: Lightweight calculator directly in chat
premissions:
  calculator.use:
    description: Access to the calculator
