name: EasyCalculator
main: fr.easycalculator.EasyCalculator
version: 6
author: _Andross
description: Lightweight calculator directly in chat
premissions:
  easycalculator.*:
    default: op
    description: Access to all the calculator
    children:
      easycalculator.operations: true
      easycalculator.functions: true
