name: EasyCalculator
main: fr.andross.EasyCalculator
version: '7.0'
author: Andross
description: Lightweight calculator directly in chat
premissions:
  easycalculator.*:
    default: op
    description: Access to all the calculator
    children:
      easycalculator.operations: true
      easycalculator.functions: true
