name: Calculator
main: fr.andross.calculator.Calculator
version: '1.1'
author: Andross
description: Powerful and lightweight calculator directly in chat
premissions:
  calculator.use:
    description: Access to the calculator
