name: EasyCalculator
main: fr.easycalculator.EasyCalculator
version: 3
author: _Andross
description: Lightweight calculator directly in chat
premissions:
  easycalculator.access:
    default: op
    description: Access to the calculator
